# Site settings
title: Over the Shoulder Reviews
# email: your-email@domain.com
description:
  "Book reviews based on what I'm able to read over the shoulders
  of commuters on the New York City subway."
baseurl: "/OtSRblog" # the subpath of your site, e.g. /blog/
url: "psweetpotato.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  psweetpotato

# Build settings
markdown: kramdown
